name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:          # allows you to run manually if needed

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render Service
        run: curl -s https://thinkbot-backend.onrender.com/ > /dev/null
